package com.demo.oms.enums;

public enum NotificationType {
    ORDER_FILLED,
    ORDER_PARTIALLY_FILLED,
    ORDER_CANCELLED,
    ORDER_REJECTED,
    ORDER_AMENDED,
    PRICE_ALERT_HIGH,
    PRICE_ALERT_LOW,
    CIRCUIT_BREAKER_HIT,
    MARGIN_CALL,
    RISK_LIMIT_BREACH,
    CORPORATE_ACTION,
    SETTLEMENT_DUE,
    IPO_ALLOTMENT,
    MARKET_OPEN,
    MARKET_CLOSE,
    SYSTEM_ALERT
}
